### ISSUE TITLE
Using translations in the Selectable interface?

### ISSUE THREAD

**Issue by mogensen** [gobuffalo/tags#136] opened 2020-11-19 20:03 UTC
Hi, 

I have a slice of structs that are selectable in a form. 
The label displayed in the select box is created by implementing the  selectable interface on the struct.
But I cannot actually translate the labels to different languages using the `i18n.Translator`, as I cannot get a context.

```go
func (c ClimbingType) SelectLabel() string {
    return T.Translate( .. ? , "climbingactivity.type."+c.typeName)
}
```

 - Is there any way to access the context?
 - Should we consider adding a SelectableWithContext interface?
 - Have I completely missed something?

**Comment by sio4** [comment] 2022-09-04 08:31
Hi, I guess you mean the `buffalo.Context` (in the sentence "way to access the context"). If then, it could depend on what you implement, but I don't think that is easily possible because that could mean coupling with Buffalo core to Tags.

I didn't think much about it but I guess you can prepare a kind of "translated instance" of `ClimbingType` before passing it to the `SelectTag(...)`. I think that could be an easy and straightforward option.

Anyway, I am about to close this issue since the issue is open for a long time without activity, but please feel free to reopen it with further questions for sharing your experiences.
Thanks

**Closed by sio4** 2022-09-04 08:31 UTC
